export const FETCH_EDUCATIONS = "FETCH_EDUCATIONS";
export const LOADING_EDUCATIONS = "LOADING_EDUCATIONS";
export const ADD_EDUCATION = "ADD_EDUCATION";
export const EDIT_EDUCATION = "EDIT_EDUCATION";
export const DELETE_EDUCATION = "DELETE_EDUCATION";
