export const FETCH_EXPERIENCES = "FETCH_EXPERIENCES";
export const LOADING_EXPERIENCES = "LOADING_EXPERIENCES";
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const EDIT_EXPERIENCE = "EDIT_EXPERIENCE";
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
